language: python
services:
  - redis-server
python:
  - '2.6'
  - '2.7'
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
matrix:
  include:
    - python: '2.7'
      env: DJANGO_VERSION=1.7
    - python: '2.7'
      env: DJANGO_VERSION=1.8
    - python: '2.7'
      env: DJANGO_VERSION=1.9
    - python: '2.7'
      env: DJANGO_VERSION=1.10
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django-redis-cache
script: python runtests.py
